version: '3'

services:
  ms-faenas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:oracle:thin:@dbcapstone_high?TNS_ADMIN=/app/oracle_wallet
      DB_USER_NAME: ADMIN
      DB_PASSWORD: 123456Qwerty@
    restart: always
