version: '3'

services:
  ms-trabajadores:
    build: ms-gestion-trabajadores
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:oracle:thin:@dbcapstone_high?TNS_ADMIN=C:/Users/HP/Desktop/Capstone/Wallet_DbCapstone
      DB_USER_NAME: ADMIN
      DB_PASSWORD: 123456Qwerty@
    volumes:
      - C:/Users/HP/Desktop/Capstone/Wallet_DbCapstone:/app/wallet
    restart: always
